linters:
  enable:
    - gosec
    - godot
    - misspell
    - stylecheck

linters-settings:
  stylecheck:
    # Select the Go version to target. The default is '1.13'.
    go: "1.21"
    checks: ["all","-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]

issues:
  exclude-use-default: false

output:
  format: colored-line-number

  # print lines of code with issue, default is true
  print-issued-lines: false

  # print linter name in the end of issue text, default is true
  print-linter-name: true